tasks:
  - name: Install Hugo and Dependencies
    before: brew install docfx && npm install && sudo apt install git-restore-mtime
    init: git restore-mtime --force
    command: docfx ./docfx.json
ports:
  - port: 1313
    onOpen: open-browser
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: false
# enable for all branches in this repo (defaults to false)
    branches: false
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
vscode:
  extensions:
    - bungcip.better-toml
    - budparr.language-hugo-vscode
    - eliostruyf.vscode-front-matter
    - valentjn.vscode-ltex