tasks:
  - name: Install docfx
    before: sh install-tools.sh 
    init: npm install
    command: npm run docfx
  - name: working terminal
    init: echo "the working terminal" 
    openMode: split-left 
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: false
    dev: false
# enable for all branches in this repo (defaults to false)
    branches: false
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
vscode:
  extensions:
    - eliostruyf.vscode-front-matter
    - valentjn.vscode-ltex