tasks:
  - name: Install mono
    before: sh install-mono.sh 
    init: mono docfx/docfx.exe docs/docfx.json --serve
  - name: working terminal
    init: echo "the working terminal"  
ports:
  - port: 8080
    onOpen: open-browser
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: false
    dev: false
# enable for all branches in this repo (defaults to false)
    branches: false
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
vscode:
  extensions:
    - eliostruyf.vscode-front-matter
    - valentjn.vscode-ltex