name: Vale Linter
description: The official GitHub Action for Vale -- install, manage, and run Vale with ease.
author: jdkato
branding:
  icon: check
  color: green

inputs:
  version:
    description: "The Vale CLI version to install."
    required: false
    default: "latest"

  files:
    description: 'The files to lint: "all" or "<some_folder>".'
    required: false
    default: ./docs/

  debug:
    description: "Log debugging information to stdout."
    required: false
    default: "false"

  reporter:
    description: "Reporter of reviewdog command [github-pr-check,github-pr-review,github-check]."
    required: false
    default: "github-pr-check"

  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    required: false
    default: "false"

  level:
    description: "Report level for reviewdog [info,warning,error]."
    required: false
    default: "error"

  filter_mode:
    description: |
      Filtering for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    required: false
    default: "added"

  vale_flags:
    description: "Space-delimited list of flags for the Vale CLI."
    required: false
    default: ""

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.version }}
    - ${{ inputs.files }}
    - ${{ inputs.debug }}
    - ${{ inputs.reporter }}
    - ${{ inputs.fail_on_error }}
    - ${{ inputs.level }}
    - ${{ inputs.filter_mode }}
    - ${{ inputs.vale_flags }}
