name: Build doc

on:
  pull_request:
    branches:
    - main
    - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          level: error
          files: docs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2

      - name: Build Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json 

      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: htmltest.yml

      - name: publish to gh for preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true    

