name: Build doc

on:
  pull_request:
    branches:
    - main
    - dev

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          fail_on_error: true
          level: error
          files: ./docs/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: ./docs/docfx.json    

