name: Publish docs

on:
  push:
    branches:
    - main

jobs:
  publish-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          level: error
          files: docs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: docs/docfx.json 

      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: htmltest.yml

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOCS_AS_CODE_DEMO }}'
          channelId: live
          projectId: docs-as-code-demo
