name: Publish docs

on:
  push:
    branches:
    - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          fail_on_error: true
          level: error
          files: ./docs/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: ./docs/docfx.json 

      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: ./docs/_site 
    
      - name: publish to gh
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true
